Make it possible to redirect to a login url unless authenticated
OliveTin/OliveTin pull request #347
Opened 2024-07-04 20:46 UTC by sdahlbac

# PR Introduction

This is an initial attempt of adding a feature to navigate to a configured url if configured and user is not authenticated.
basically

As a end user I want to end up on a login page if I am not authenticated
so that it is clear that I am not authenticated and can easily log in again.

I do not know the codebase well yet, so it is quite possible that I have done something stupid and/or missed something obvious.

Opening PR early for feedback.

Known issues: 
- `make daemon-unittests` panic for some reason
- `make daemon-compile`: go: unsupported GOOS/GOARCH pair darwin/arm
- docs

# Checklist
Please put a X in the boxes as evidence of reading through the checklist.

- [x] I have forked the project, and raised this PR on a feature branch.
- [x] `make githooks` has been run, and my git commit message was accepted by the git hook.
- [ ] `make daemon-compile` runs without any issues.
- [x] `make daemon-codestyle` runs without any issues.
- [ ] `make daemon-unittests` runs without any issues.
- [x] `make webui-codestyle` runs without any issues.
- [x] I understand and accept the [AGPL-3.0 license](LICENSE) and [code of conduct](CODE_OF_CONDUCT.md), and my contributions fall under these.

2024-07-06 21:19 UTC, jamesread commented
@sdahlbac , thanks SO much for taking a look at this. I think this is totally reasonable to add to OliveTin. I've just taken a quick look on my phone and it all looks pretty good.

Just a couple of little bits;

1. Maybe we rethink the config naming, there might be a time when we want to present people with a button to click to go to the login page, instead of actually redirecting, in the future.
2. It looks like some imports moved around unecessarily, would you mind reverting those little changes to keep the PR to only the essential code changes? 
3. Could you investigate if sending a redirect header, instead of serving the webui, would be easily doable? I think OAuth prefers this technique, and it stops the "flash of the UI before redirect" kind of ugly user experience.

On the whole though, thanks so much for putting a good amount of thought into this, and raising the PR! Really like the look of it, and keen to continue working with you on it!

2024-07-08 19:17 UTC, sdahlbac commented
1) naming is hard, that was the best I could think of at the time, do you have a better name in mind?

2) I can probably do that, but I suspect I have to fight tooling to not make the same changes again (since I did not make those changes explicitly myself)

3) AFAIK this is not really possible, backend can respond with a 30x redirect alright, but that only applies to a particular request, we'd want to navigate somewhere different entirely.

2024-08-29 08:05 UTC, sdahlbac commented
@jamesread back after vacations and what not, but rebased this on main and reverted the imports moving around

2024-10-10 21:25 UTC, jamesread requested changes
Check the comments.

2024-10-10 21:25 UTC, jamesread commented on internal/config/config.go
> +	UrlOnUnauthenticated            string
It would be good to keep auth related settings starting with "Auth", and grouping them together, and I think there is value in splitting this up into two settings, allowing some future expansion options. How about `AuthLoginUrl`, and `AuthLoginGuest: true`?

2024-10-10 21:25 UTC, jamesread commented on webui.dev/main.js
> +      window.location.href = window.settings.UrlOnUnauthenticated
Will need to check if the error gives a 401 or not.

2024-10-10 21:25 UTC, jamesread commented on internal/grpcapi/grpcApi.go
> +		return nil, errors.New("unauthenticated")
`return nil, status.Errorf(codes.PermissionDenied, "Unauthenticated")`

Note that I'm not entirely sure if this will return a 401, or a 403.

2024-10-10 21:25 UTC, jamesread commented
Hey @sdahlbac , thanks very much for your patience. I actually had a code review soon after you posted this PR, but annoyingly I left it in draft on GitHub and didn't submit it back to you. That was my mistake, apologies. I'd made some suggested names for variables and similar. 

I'm actually working on both OAuth and Username/Password support for OliveTin at the moment, and I've recently just made some patches to ACLs and stuff to handle Guests a lot better. 

I'm leaning to a config that looks like this;

```
authAllowGuest: false
authLoginUrl: "http://...."
```

2024-10-10 21:27 UTC, jamesread commented on internal/grpcapi/grpcApi.go
>  	res.AuthenticatedUser = user.Username
`user.Username` is now guaranteed to be `guest` if they've not logged in.

2024-10-11 17:37 UTC, jamesread commented
@sdahlbac awesome, merged! Thanks very much indeed for your time ☺️

2024-10-11 17:42 UTC, merged