feature: allow configurable title
OliveTin/OliveTin pull request #67
Opened 2022-06-30 15:59 UTC by strazto

Resolves #15 

# Checklist
Please put a X in the boxes as evidence of reading through the checklist.

- [x] I have forked the project, and raised this PR on a feature branch. 
- [ ] `make githooks` has been run, and my git commit message was accepted by the git hook.
- [ ] `make daemon-compile` runs without any issues.
- [ ] `make daemon-codestyle` runs without any issues.
- [ ] `make daemon-unittests` runs without any issues.
- [ ] `make webui-codestyle` runs without any issues. 
- [x] I understand and accept the [AGPL-3.0 license](LICENSE) and [code of conduct](CODE_OF_CONDUCT.md), and my contributions fall under these.

2022-07-01 22:22 UTC, jamesread commented
Hey @matthewstrasiotto , thanks for the time spent in doing this - much appreciated :-) I've not had much time to work on OliveTin recently, so any contribution from others is always welcome. 

I'd like to see a screenshot of what the page looks like by default - a default unstyled H1 element might look pretty awful. My main workstation is powered off at the moment, but I'll take a look in the morning :-)

2022-10-21 13:32 UTC, jonny7read commented on webui/main.js
> +    document.title = setttings.pageTitle;
Looks like you've got a typo here on `setttings`, should be `settings`
```suggestion
    document.title = settings.pageTitle;
```

2022-10-21 13:37 UTC, jonny7read requested changes
Typo

2022-11-03 14:41 UTC, jamesread commented
Hey @strazto , this is long overdue, sorry for the late review. Life has just been busy!

I just did a quick merge commit to bring this up to date with main, and built it, and this is the screenshot I was curious about;

![image](https://user-images.githubusercontent.com/2025715/199691932-58714b4a-7ee8-4606-8f25-e2deb6cf6f20.png)

I obviously would like to make this prettier! I have been working on a new sidebar feature as part of the UI update / entity support coming soon, and think the "title" fits pretty nicely in the "sidebar". 

![image](https://user-images.githubusercontent.com/2025715/199751325-fa32973e-cc59-4147-b3e7-c71a5ce350cb.png)

I'm not sure if the title should be an overall "global" title, or if it should show the current "dashboard title". Need to give that some thought.

2022-11-03 22:14 UTC, jamesread approved these changes
LGTM! Thanks @strazto !

2022-11-03 22:14 UTC, merged